version: '3.8'

services:
  mongodb:
    container_name: mongo-prod
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - my-network

  rabbitmq:
    container_name: rabbit-prod
    image: rabbitmq:3-management  # Use the official RabbitMQ image with management plugin
    ports:
      - "5672:5672"  # Default port for RabbitMQ
      - "15672:15672"  # Management console port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - my-network

  app:
    container_name: back-prod
    image: app-net7:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO__CONNECTIONSTRING: "mongodb://mongodb:27017"
      MONGO__DATABASE: "a82Moto"
    ports:
      - "8080:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
