version: '3.8'

services:
  mongodb:
    container_name: mongo-prod
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - my-network

  rabbitmq:
    container_name: rabbit-prod
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
